parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: ecommerce
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 03d25bbbec370ac932d028ac22de14c1646b3c90
    database_path: null
